version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: albaraka-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - albaraka-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: albaraka-backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_DIR: ${UPLOAD_DIR}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - albaraka-network
    volumes:
      - upload_data:/app/uploads

volumes:
  postgres_data:
  upload_data:

networks:
  albaraka-network:
    driver: bridge
