version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: albaraka-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - albaraka-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: albaraka-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - albaraka-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: albaraka-backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_DIR: ${UPLOAD_DIR}
      KEYCLOAK_ENABLED: ${KEYCLOAK_ENABLED:-true}
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/albaraka
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - albaraka-network
    volumes:
      - upload_data:/app/uploads

volumes:
  postgres_data:
  upload_data:

networks:
  albaraka-network:
    driver: bridge
